produits:
    path:     /boutique
    defaults: { _controller: EcommerceBundle:Produits:produit }

presentation:
    path:     /boutique/produit
    defaults: { _controller: EcommerceBundle:Produits:presentation }

panier:
    path:     /boutique/panier
    defaults: { _controller: EcommerceBundle:Panier:panier }

livraison:
    path:     /boutique/panier/livraison
    defaults: { _controller: EcommerceBundle:Panier:livraison }

validation:
    path:     /boutique/panier/validation
    defaults: { _controller: EcommerceBundle:Panier:validation }


test:
    path:     /boutique/test
    defaults: { _controller: EcommerceBundle:Test:testFormulaire }